version: 2
jobs:
    build:
        working_directory: ~/konec-dejin
        docker:
            - image: circleci/node:10.16.0-browsers
        steps:
            - checkout:
                path: ~/konec-dejin
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH} 
            - run:
                name: Show current directory
                command: pwd
            - run:
                name: Go to app
                command: cd app    
            - run:
                name: Show current directory
                command: pwd    
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Building
                command: npm run build-prod
            - run:
                name: Go to functions
                command: cd ../functions
            - run:
                name: Show current directory
                command: pwd    
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Install Firebase
                command: sudo npm install -g firebase-tools
            - run:
                name: Go to root
                command: cd ..
            - run:
                name: Show current directory
                command: pwd   
            - run:
                name: Deploy Master to Firebase
                command: firebase deploy --token=$FIREBASE_TOKEN       
            
workflows:
    version: 2
    -deploy:
        jobs:
        - build