version: 2
jobs:
    build:
        working_directory: ~/konec-dejin/app
        docker:
            - image: circleci/node:10.16.0-browsers
        steps:
            - checkout:
                path: ~/konec-dejin
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH} 
            - run:
                name: Show current directory
                command: pwd
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Building
                command: npm run build-prod
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist
                    - package.json
                    - firebase.json
                    - .firebaserc
    deploy:
        docker:
            - image: circleci/node:10.16.0-browsers-legacy
        working_directory: ~/konec-dejin
        steps:
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH} 
            - restore_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install Firebase
                command: sudo npm install -g firebase-tools
            - run:
                name: Deploy Master to Firebase
                command: firebase deploy --token=$FIREBASE_TOKEN

workflows:
    version: 2
    -deploy:
        jobs:
        - build
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master